name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Run on BIOS
        run: USE_UEFI=0 cargo run
      - name: Run on UEFI
        run: USE_UEFI=1 cargo run
